domain_path: D:\Doan2_Vitis\SOC_platform\export\SOC_platform\sw\standalone_microblaze_riscv_0
app_src_dir: D:\VitisEmbbed\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
