# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SOC/SOC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC || ORIG_REF_NAME==SOC} -quiet] -quiet

# IP: bd/SOC/ip/SOC_mig_7series_0_0_7/SOC_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_mig_7series_0_0 || ORIG_REF_NAME==SOC_mig_7series_0_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_0/SOC_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_axi_gpio_0_0/SOC_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_axi_gpio_0_0 || ORIG_REF_NAME==SOC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_axi_uartlite_0_0/SOC_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_axi_uartlite_0_0 || ORIG_REF_NAME==SOC_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_xbar_0/SOC_microblaze_riscv_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_0/SOC_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_intc_0/SOC_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_xlconcat_0/SOC_microblaze_riscv_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_xlconcat_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_xlconcat_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_mdm_1_0/SOC_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_mdm_1_0 || ORIG_REF_NAME==SOC_mdm_1_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_rst_mig_7series_0_100M_0/SOC_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==SOC_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_rst_mig_7series_0_200M_0/SOC_rst_mig_7series_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==SOC_rst_mig_7series_0_200M_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_axi_timer_0_0/SOC_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_axi_timer_0_0 || ORIG_REF_NAME==SOC_axi_timer_0_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_4/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_4 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_4} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_0/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_1 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_1} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_3/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_3 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_us_3} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_1 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_1} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_0/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_0/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_1 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_1} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_2 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_2} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_2 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_2} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_0/SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_0 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_cc_0} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_3/SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_3 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_ds_3} -quiet] -quiet

# IP: bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_3/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_3 || ORIG_REF_NAME==SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_3} -quiet] -quiet

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/SOC_ooc.xdc
