# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.srcs/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1.xci
# IP: The module: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.srcs/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1.xci
# IP: The module: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1/SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
