# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.srcs/sources_1/bd/SOC/ip/SOC_axi_timer_0_0/SOC_axi_timer_0_0.xci
# IP: The module: 'SOC_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_axi_timer_0_0/SOC_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_axi_timer_0_0/SOC_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.srcs/sources_1/bd/SOC/ip/SOC_axi_timer_0_0/SOC_axi_timer_0_0.xci
# IP: The module: 'SOC_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_axi_timer_0_0/SOC_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_axi_timer_0_0/SOC_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
