# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.srcs/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2.xci
# IP: The module: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.srcs/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2.xci
# IP: The module: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/SOC_DoAn2/SOC_DoAn2/SOC_DoAn2.gen/sources_1/bd/SOC/ip/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2/SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_microblaze_riscv_0_axi_periph_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
